try {
        cout << closestToZero({}) << endl;
    } catch(const exception & e) {
        cerr << e.what() << endl;
    }